### ISSUE TITLE
seq-data-to-lane-bam failed to skip all input bams when process multiple input bams

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/dna-seq-processing-tools#107]
## Detailed Description
When there are multiple input bams, [here](https://github.com/icgc-argo/dna-seq-processing-tools/blob/master/tools/seq-data-to-lane-bam/seq-data-to-lane-bam.py#L189) needs to skip all the input bams. Otherwise the job will fail and report:
`Error: unable to find read group info for rg_id in the supplied metadata (SONG Analysis)`

## Approach to address this
Let the `samtools split` generate the output into separate subfolder so as to avoid processing the input bams. 

## Testing
Need to add a new test to cover the case

**Comment by junjun-zhang** [comment]
addressed by #108 and #109
