### ISSUE TITLE
Change `tempdir` from `Path` to `Val` inputs of tools: `bwa-mem-aligner` and `bam-merge-sort-markdup`

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/dna-seq-processing-tools#122]
Did some tests in `rdpc-qa` by resume the alignment jobs. Here are some observations:
- when provide and use the `temp_dir` , the job will resume from `bwa-mem align` step although I cancelled it at song/score uploading task.
- when do NOT use the `temp_dir`, the job will resume as expected from `payload generation`

So pretty much we can confirm that the unexpected resume behaviour is because of using `temp_dir` as one of the input params for task `bwa-mem`. As this param `temp_dir` is container based, nextflow will regard the input params have some changes in this case. 

Ref: 
- https://www.nextflow.io/blog/2019/troubleshooting-nextflow-resume.html
- https://www.nextflow.io/blog/2019/demystifying-nextflow-resume.html

**Comment by junjun-zhang** [comment]
@lindaxiang, there is a need to have some indication to trigger the mounting of k8s emptyDir as `/icgc-argo-scratch` on a pod. If `temp_dir` param is removed, what else can we use? One possibility is to change `params.temp_dir` from path to just a string val, this way NF will not need to mount anything. Not sure whether this helps solving the resume issue, but at least it's simple enough to try out.

Just a note here, the mount of k8s emptyDir isn't a standard Nextflow feature, it's something we added to RDPC k8s. This might or might not be related to the unexpected resume behaviour.

**Comment by lindaxiang** [comment]
Thanks @junjun-zhang for the information. 
If I understand correctly, `temp_dir` param is used to trigger the mounting of k8s emptyDir when starting a pod. So we do need to keep it in the task params. But we can still remove it from the inputs of the task, right? 

Previously I was thinking to use python wrapper to detect whether the `temp_dir` exist or not instead of relying on the given inputs. But I think the solution you provide may be even better.

**Comment by junjun-zhang** [comment]
As I am not aware of the underlying details, two things I am not certain: 1) whether a `val` input for `temp_dir` is able to trigger k8s emptyDir mounting; 2) whether it will solve the resume issue. But again, it's worth a shot.

In any case, checking whether the specified `temp_dir` exists in the python code is a good idea.

**Comment by lindaxiang** [comment]
@junjun-zhang I just talked to Alex briefly. He said `empty_dir` always gets mounted no matter what, but temp_dir is used for steps that make use of it if provided. That means all our pods created in all jobs have `temp_dir` mounted. It is the task’s business to use it or not.

**Comment by junjun-zhang** [comment]
in that case, changing input from `path` to `val` for `params.temp_dir` should work.

The other consideration we need to keep in mind is that all of ARGO workflows are meant to be able to run in other platforms by other users, so allowing them to specific whether and what temp dir to use is still a good thing to support. For example, we mount the tempdir as `/icgc/argo/scratch`, one user may need to use a different path

**Comment by akachru-github** [comment]
New version [1.9.0](https://github.com/icgc-argo/dna-seq-processing-wfs/releases/tag/1.9.0) has been tested and released to address the issue.

**Comment by akachru-github** [comment]
This will need to be deployed to production via: https://github.com/icgc-argo/workflow-roadmap/issues/178
