### ISSUE TITLE
Hashbang headers

### ISSUE THREAD

**Issue by ewels** [icgc-argo/dna-seq-processing-tools#71]
Super minor thing, but your nextflow files currently have the following header lines:
https://github.com/icgc-argo/dna-seq-processing-tools/blob/0702bad62ff7949801d9be5a3e72e4932ea787b8/tools/seq-validation/seq-validation.nf#L1

This doesn't matter, as it's ignored by nextflow when it loads the file. However, technically I think it should probably be the following instead:

```bash
#!/usr/bin/env nextflow
```

The only reason I noticed this is that your source files are syntax-highlighted as `bash` code on GitHub. If you use the above hashbang then I think GitHub should now be clever enough to format the code as Nextflow instead (see for example [nf-core/rnaseq main.nf](https://github.com/nf-core/rnaseq/blob/master/main.nf)).

If you want to use GitHub syntax highlighting on other files, you can use a [`.gitattributes`]( https://github.com/nf-core/rnaseq/blob/master/.gitattributes) file. This is how we get nextflow formatting for our `.config` files:

```git-attributes 
*.config linguist-language=nextflow
```

**Comment by junjun-zhang** [comment]
Thanks @ewels for reporting this, we will take a look.

**Comment by junjun-zhang** [comment]
all tasks  completed
