### ISSUE TITLE
add parameters to config JVM options when using Picard tools

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/dna-seq-processing-tools#76]
## Detailed Description

Picard is a set of command line tools written in Java. The typical tools are invoked as follows:
`java jvm-args -jar picard.jar PicardToolName 
	OPTION1=value1 
	OPTION2=value2`

`jvm-args` are arguments that are specific to Java, not Picard. 
Although Picard does not provide guidance for specifying JVM (Java Virtual Machine) arguments except for specifying memory: most of the commands are designed to run in 2GB of JVM, so they recommend using the JVM argument -Xmx2g.

When running the tools in the scenario of k8s, it's better to have the option to config the JVM arguments at workflow or job level. 

## Possible Implementation

We can pass the `task.cpus` and `task.memory` into the tool, and let the `python` tool to calculate and configure  `jvm-args` accordingly.

**Comment by junjun-zhang** [comment]
addressed by #81
